**The outputs of the commands below will change depending on which "channel" or "environment" was used to launch this jupyter notebook.**

In [6]:
import sys
sys.version

'3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]'

In [7]:
import matplotlib
matplotlib.__version__

'3.1.3'

In [8]:
import numpy
numpy.__version__

'1.18.1'

In [9]:
import scipy
scipy.__version__

'1.4.1'

scipy.spatial.transform is [present in 1.2.0](https://docs.scipy.org/doc/scipy-1.2.0/reference/spatial.transform.html#rotations-in-3-dimensions) but [absent in  1.1.0](https://docs.scipy.org/doc/scipy-1.1.0/reference/spatial.transform.html#rotations-in-3-dimensions).

Attempting a rotation example from the [SciPy 1.4.1 documentation](
https://docs.scipy.org/doc/scipy-1.4.1/reference/generated/scipy.spatial.transform.Rotation.html?highlight=rotation#scipy.spatial.transform.Rotation):

In [11]:
import numpy as np
from scipy.spatial.transform import Rotation as R
r = R.from_quat([0, 0, np.sin(np.pi/4), np.cos(np.pi/4)])
print(r.as_matrix())
print(r.as_rotvec())
print(r.as_euler('zyx', degrees=True))
print(r.as_euler('xyz', degrees=True))

[[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]
[0.         0.         1.57079633]
[90.  0.  0.]
[ 0.  0. 90.]
